#!/usr/bin/env python3
"""AMP P2b fetch-rate probe generator.

Emits:
  loop_local.kla — countdown loop (N iterations), label jumps, runs at 0
                   (core-2 local BRAM): the reference fetch rate.
  loop_ddr.kla   — the same loop with the backward jump as an ABSOLUTE hex
                   literal fixed up for placement at DDR_BASE (two-pass:
                   assemble with a label first, read the resolved offset
                   from the listing, re-emit).  Runs from the cached text
                   window: the cache-effectiveness measurement.
  core1_p2btest.kla — runs both on core 2, timing each via r_clock_ms
                   (0xF00F_0040); prints "L=<hex ms>" and "D=<hex ms>".

usage: gen_p2b.py <iters>  (then assemble outputs with klausscc)"""
import re
import subprocess
import sys

K = "/home/graham/Documents/src/klausscc/target/release/klausscc"
DDR_BASE = 0x07E00000
ITERS = int(sys.argv[1]) if len(sys.argv) > 1 else 1000000

LOOP = """// %s — GENERATED by gen_p2b.py (%d iterations)
_start
SETR E %d
lp:
MINUSV E 1
JMPNZ lp:
HALT
"""

open("loop_local.kla", "w").write(LOOP % ("loop_local", ITERS, ITERS))

# Two-pass: resolve the label offset, then re-emit with the absolute target.
open("loop_ddr.kla", "w").write(LOOP % ("loop_ddr(pass1)", ITERS, ITERS))
subprocess.run([K, "--input", "loop_ddr.kla", "-o", "loop_ddr.txt"],
               check=True, capture_output=True)
off = None
for line in open("loop_ddr.txt.code"):
    m = re.match(r"0x([0-9A-Fa-f]{8}):\s+[0-9A-F ]+?\s+-- JMPNZ", line)
    if m:
        jaddr = int(m.group(1), 16)
    m2 = re.search(r"-- lp:", line)
for line in open("loop_ddr.txt.code"):
    m = re.match(r"0x([0-9A-Fa-f]{8}): .* -- JMPNZ lp:", line)
    if m:
        words = line.split(":")[1].split("--")[0].split()
        off = int(words[1], 16)          # the resolved label immediate
if off is None:
    sys.exit("could not resolve lp: offset")
src = LOOP % ("loop_ddr", ITERS, ITERS)
src = src.replace("JMPNZ lp:", "JMPNZ 0x%X" % (DDR_BASE + off))
src = src.replace("lp:\n", "")           # label no longer needed
open("loop_ddr.kla", "w").write(src)
print("loop_ddr: label offset 0x%X -> absolute 0x%X" % (off, DDR_BASE + off))

# --------------------------------------------------------------- core-1 ----
L = []
L.append("// core1_p2btest — GENERATED (gen_p2b.py): fetch-rate probe.")
L.append("// Times a %d-iteration loop on core 2: local BRAM vs DDR text" % ITERS)
L.append("// window (through the P2b read cache).  Prints hex ms for each.")
L.append("_start")


def emit64(reg, tmp, val):
    hi, lo = val >> 32, val & 0xFFFFFFFF
    L.append("SETR %s 0x%X" % (reg, hi))
    L.append("SHLV %s 32" % reg)
    L.append("SETR %s 0x%X" % (tmp, lo))
    L.append("SHLV %s 32" % tmp)
    L.append("SHRV %s 32" % tmp)
    L.append("ORR %s %s %s" % (reg, reg, tmp))


def putstr(s):
    for ch in s:
        L.append("SETR A %d" % ord(ch))
        L.append("CALL putc:")


def run_timed(start_pc, tag):
    # H := clock_ms before; run; poll parked; D := clock_ms after - H
    L.append("SETR B 0xF00F0040")
    L.append("MEMREADRR H B")
    L.append("SETR G 0xF0100008")
    L.append("SETR A 0x%X" % start_pc)
    L.append("MEMSET64 A G")
    L.append("SETR G 0xF0100000")
    L.append("SETR A 0")                 # RUN 0 first: a clean 0->1 edge even
    L.append("MEMSET64 A G")             # if core 2 was left parked with RUN=1
    L.append("SETR A 1")
    L.append("MEMSET64 A G")
    L.append("%s_park:" % tag)
    L.append("MEMREADRR D G")
    L.append("COPY A D")
    L.append("ANDV A 2")
    L.append("CMPRV A 2")
    L.append("JMPNE %s_park:" % tag)
    L.append("SETR A 0")
    L.append("MEMSET64 A G")             # RUN=0
    L.append("SETR B 0xF00F0040")
    L.append("MEMREADRR D B")
    L.append("SUBR D D H")
    putstr(tag + "=")
    L.append("CALL print_hex64:")
    putstr("\n")


# window-load loop_local (image inlined at assemble time by including its
# dwords — filled in by the runner via a placeholder substitution)
L.append("@@WINDOW_LOAD_LOCAL@@")
run_timed(0x20, "L")
L.append("@@DDR_STORE_LOOP@@")
L.append("SETR B 0xF0050000")            # FLUSH
L.append("SETR A 2")
L.append("MEMSET64 A B")
L.append("SETR B 0xF0050010")
L.append("mnt_wait:")
L.append("MEMREADRR C B")
L.append("ANDV C 1")
L.append("CMPRV C 0")
L.append("JMPNE mnt_wait:")
run_timed(DDR_BASE + 0x20, "D")
putstr("P2B DONE\n")
L.append("HALT")
L.append("")
L.append("// print_hex64: D printed as 16 hex digits (destroys A,C,E)")
L.append("print_hex64:")
L.append("SETR E 16")
L.append("ph_loop:")
L.append("ROLV D 4")
L.append("COPY A D")
L.append("ANDV A 0xF")
L.append("CMPRV A 10")
L.append("JMPULT ph_digit:")
L.append("ADDV A 55")
L.append("JMP ph_out:")
L.append("ph_digit:")
L.append("ADDV A 48")
L.append("ph_out:")
L.append("CALL putc:")
L.append("MINUSV E 1")
L.append("JMPNZ ph_loop:")
L.append("RET")
L.append("")
L.append("putc:")
L.append("SETR B 0xF0010010")
L.append("putc_wait:")
L.append("MEMREADRR C B")
L.append("ANDV C 1")
L.append("CMPRV C 0")
L.append("JMPNE putc_wait:")
L.append("SETR B 0xF0010000")
L.append("MEMSET8 A B")
L.append("RET")

open("core1_p2btest.kla.tmpl", "w").write("\n".join(L) + "\n")
print("core1_p2btest.kla.tmpl written (needs placeholder fill)")
