#!/usr/bin/env python3
"""Generate core1_p1test.kla: a core-1 program that loads the embedded
core-2 image through the AMP mailbox window (device 0x010), starts core 2,
drains its log FIFO to the real UART, and prints P1 PASS/FAIL.
usage: gen_loader.py <image.mem> <expect_len> <out.kla>"""
import sys

mem, explen, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]
dwords = [int(l, 16) for l in open(mem) if l.strip()]

L = []
L.append("// core1_p1test — GENERATED by gen_loader.py: AMP P1 board gate.")
L.append("// Loads %d dwords of hello_core2 into core 2 via the mailbox window," % len(dwords))
L.append("// starts core 2, forwards %d log bytes to the UART, checks HALT park." % explen)
L.append("_start")
L.append("SETR G 0xF0100010")            # WIN_ADDR
L.append("SETR A 0")
L.append("MEMSET64 A G")
L.append("SETR G 0xF0100018")            # WIN_DATA (auto-increment)
for dw in dwords:
    hi, lo = dw >> 32, dw & 0xFFFFFFFF
    L.append("SETR A 0x%X" % hi)
    L.append("SHLV A 32")
    L.append("SETR B 0x%X" % lo)
    L.append("SHLV B 32")                # zero-extend lo regardless of SETR
    L.append("SHRV B 32")                # sign behaviour
    L.append("ORR A A B")
    L.append("MEMSET64 A G")
L.append("SETR G 0xF0100008")            # START_PC
L.append("SETR A 0x20")
L.append("MEMSET64 A G")
L.append("SETR G 0xF0100000")            # CTRL: RUN
L.append("SETR A 1")
L.append("MEMSET64 A G")
L.append("SETR E %d" % explen)
L.append("SETR G 0xF0100020")            # C2_LOG
L.append("drain_wait:")
L.append("MEMREADRR D G")
L.append("COPY A D")
L.append("SHRV A 8")
L.append("ANDV A 1")
L.append("CMPRV A 1")
L.append("JMPNE drain_wait:")            # no byte yet — poll again
L.append("COPY A D")
L.append("ANDV A 0xFF")
L.append("CALL putc:")
L.append("SETR A 0")
L.append("MEMSET64 A G")                 # pop
L.append("MINUSV E 1")
L.append("JMPNZ drain_wait:")
L.append("SETR G 0xF0100000")            # CTRL readback: expect 0x3 (HALT park)
L.append("park_wait:")
L.append("MEMREADRR D G")
L.append("COPY A D")
L.append("ANDV A 2")
L.append("CMPRV A 2")
L.append("JMPNE park_wait:")
L.append("ANDV D 0x1F")
L.append("CMPRV D 3")
L.append("JMPNE fail:")
for ch in "P1 PASS\n":
    L.append("SETR A %d" % ord(ch))
    L.append("CALL putc:")
L.append("HALT")
L.append("fail:")
for ch in "P1 FAIL\n":
    L.append("SETR A %d" % ord(ch))
    L.append("CALL putc:")
L.append("HALT")
L.append("")
L.append("// putc: send A's low byte over the real UART (destroys B,C)")
L.append("putc:")
L.append("SETR B 0xF0010010")
L.append("putc_wait:")
L.append("MEMREADRR C B")
L.append("ANDV C 1")
L.append("CMPRV C 0")
L.append("JMPNE putc_wait:")
L.append("SETR B 0xF0010000")
L.append("MEMSET8 A B")
L.append("RET")

open(out, "w").write("\n".join(L) + "\n")
print("%s: %d lines, %d image dwords" % (out, len(L), len(dwords)))
