#!/usr/bin/env python3
# gen_probe.py — generate the M7 hazard-attribution probe (haz_probe_<profile>.kla).
#
# WHY a hand-assembled .kla and not an edit to perf_baseline.c:
#   * perf_baseline.elf is the PINNED A/B baseline (perf/METHOD.md "stale-ELF trap").
#     Recompiling it to add counter reads would perturb the very reference we compare
#     against.  A standalone probe is a non-perturbing instrument.
#   * It assembles with klausscc's built-in ISA-v2 table, runs on both the emulator
#     (control-flow oracle) and the board (real magnitudes), with no cross-repo build.
#
# WHAT it measures: the M6 pipeline hazard counters (0xF00D_00B0..00E8) plus cycles
# (0x08) and retired instructions (0x10), decomposed PER KERNEL.  Each kernel is an
# asm reproduction of the corresponding perf_baseline.c micro-kernel's *algorithmic*
# hazard signature (the same dependency/branch/memory pattern), so the attribution is
# driven by measurement rather than estimate.  Absolute MEM_WAIT is a lower bound vs
# the fully-compiled kernels (no register-spill traffic); the RELATIVE split across
# hazard classes — which is what the M7 split-I/D + I-cache decision turns on — is the
# robust signal.
#
# Idiom per kernel (mirrors perf_baseline.c bench()):  clear counters -> run -> read.
#   PERF_CTRL (0xF00D_0000) bit0 is write-1-auto-clear and zeroes EVERY perf counter,
#   including the M6 hazard set (KlaussCPU.sv w_perf_stat_clear).
#
# Output: one line per kernel, 11 fields, each a fixed 16-hex-digit (64-bit) value,
# concatenated (self-delimiting — the parser slices every 16 chars):
#   [id, cycles, instr, STALL_DATA, STALL_LOADUSE, STALL_FLAGS, STALL_SP,
#    STALL_MULDIV, BRANCH_FLUSH, IF_MISS, MEM_WAIT]
#
# Register clobber contract (helpers): putc clobbers B,C ; puthex16 clobbers A,B,C,F,H
# and READS E ; dump/dump_at use D(id),G(addr),E(value).  Kernels run between calls so
# they may use any register freely.
#
# usage:  ./gen_probe.py sim   > haz_probe_sim.kla
#         ./gen_probe.py board > haz_probe_board.kla

import sys

PROFILES = {
    # small: fits in L1, few iters — SoC-sim plumbing check only (xsim is slow)
    "sim":   dict(SP=0x08000000, BUF=0x00100000,
                  ALU=200, MEM_WORDS=1024, MEM_REPS=1, CHASE=1024,
                  BR=200, FIB=12, MD=200),
    # board: working sets > 64 KiB L1, iters close to perf_baseline.c
    "board": dict(SP=0x08000000, BUF=0x02000000,
                  ALU=200000, MEM_WORDS=32768, MEM_REPS=4, CHASE=200000,
                  BR=500000, FIB=28, MD=50000),
}

# DDR scratch for the counter snapshot (10 doublewords; below code-free BUF,
# in the tb_soc low DDR model and valid on the board).
SCRATCH = 0x00080000
# MMIO
PERF_CTRL = 0xF00D0000
CYCLES    = 0xF00D0008
INSTR     = 0xF00D0010
HAZ = [0xF00D00B0, 0xF00D00B8, 0xF00D00C0, 0xF00D00C8,
       0xF00D00D0, 0xF00D00D8, 0xF00D00E0, 0xF00D00E8]
DUMP_ADDRS = [CYCLES, INSTR] + HAZ  # 10 counter reads after the id


def hx(v):
    return f"0x{v:X}"


def gen(p):
    L = []
    a = L.append
    a("// haz_probe_%s.kla — GENERATED by gen_probe.py. Do not edit by hand." % p_name)
    a("// M7 hazard-attribution probe: per-kernel dump of 0xF00D_00B0..00E8 (+cyc,instr).")
    a("// Fields/line (16 hex each): id cyc instr DATA LOADUSE FLAGS SP MULDIV BRFLUSH IFMISS MEMWAIT")
    a("_start")
    a(f"SETR A {hx(p['SP'])}")
    a("SETSP A")
    # NB: no DELAYV settle here — the pipeline's U_DELAY spin hangs in tb_soc
    # (dly_on/dly_cnt, pipeline_core.sv ~L582; unexercised by the ELF regression).
    # The boot loader already provides UART settle time.
    a("")
    # kernel dispatch: (setup_call_or_None, kernel_label, id)
    seq = [
        (None,          "k_alu",    0),
        (None,          "k_mem",    1),
        ("build_perm",  "k_chase",  2),
        (None,          "k_branch", 3),
        (None,          "k_fib_top",4),
        (None,          "k_muldiv", 5),
    ]
    for setup, klabel, kid in seq:
        if setup:
            a(f"CALL {setup}:")
        a("CALL clear_perf:")
        a(f"CALL {klabel}:")
        a(f"SETR D {kid}")
        a("CALL dump:")
        a("")
    a("HALT")
    a("")

    # ---------------- helpers ----------------
    a("// ---- putc: transmit low byte of A. clobbers B,C ----")
    a("putc:")
    a("SETR B 0xF0010010")     # UART_STATUS
    a("putc_wait:")
    a("MEMGET32 C B")
    a("ANDV C 1")              # TX_BUSY
    a("CMPRV C 0")
    a("JMPNE putc_wait:")
    a("SETR B 0xF0010000")     # UART_TX
    a("MEMSET8 A B")
    a("RET")
    a("")
    a("// ---- puthex16: print E as 16 hex digits (MSB first). clobbers A,B,C,F,H ----")
    a("puthex16:")
    a("SETR F 64")
    a("puthex16_loop:")
    a("MINUSV F 4")
    a("SHRR A E F")            # A = E >> F
    a("ANDV A 0xF")
    a("COPY H A")
    a("ADDV A 0x30")
    a("CMPRV H 10")
    a("JMPULT puthex16_skip:")
    a("ADDV A 7")             # 'A'..'F'
    a("puthex16_skip:")
    a("CALL putc:")
    a("CMPRV F 0")
    a("JMPNE puthex16_loop:")
    a("RET")
    a("")
    a("// ---- crlf ----")
    a("crlf:")
    a("SETR A 0x0D")
    a("CALL putc:")
    a("SETR A 0x0A")
    a("CALL putc:")
    a("RET")
    a("")
    a("// ---- clear_perf: PERF_CTRL bit0 self-clearing -> zero all perf counters ----")
    a("clear_perf:")
    a(f"SETR B {hx(PERF_CTRL)}")
    a("SETR A 1")
    a("MEMSET32 A B")
    a("RET")
    a("")
    a("// ---- dump: D=kernel id.  CRITICAL: snapshot ALL counters into a DDR")
    a("//      scratch array BEFORE any UART, exactly like perf_baseline.c bench()")
    a("//      (printing busy-waits thousands of cycles per byte and each poll is")
    a("//      an MMIO load — printing inside the read window corrupts IF_MISS/")
    a("//      MEM_WAIT with the dump's own overhead).  Then print from scratch.")
    a("dump:")
    a(f"SETR I {hx(SCRATCH)}")          # scratch base
    for k, addr in enumerate(DUMP_ADDRS):
        a(f"SETR G {hx(addr)}")
        a("MEMGET64 E G")               # E = counter
        a("MEMSET64 E I")               # scratch[k] = E
        a("ADDV I 8")
    # print phase (outside the measured window)
    a("COPY E D")
    a("CALL puthex16:")                 # id
    a(f"SETR I {hx(SCRATCH)}")
    a(f"SETR J {len(DUMP_ADDRS)}")      # count
    a("dump_print:")
    a("MEMGET64 E I")
    a("CALL puthex16:")
    a("ADDV I 8")
    a("MINUSV J 1")
    a("CMPRV J 0")
    a("JMPNE dump_print:")
    a("CALL crlf:")
    a("RET")
    a("")

    # ---------------- kernels ----------------
    # k_alu: dependent 64-bit ALU chain (perf_baseline.c k_alu)
    a("// ---- k_alu: a+=b; a^=(a<<7); a-=(b>>3); b+=a; b^=(b<<11); b+=i ----")
    a("k_alu:")
    a("SETR64 A 0x0123456789ABCDEF")   # a
    a("SETR64 B 0xFEDCBA9876543210")   # b
    a("SETR C 0")                      # i
    a(f"SETR D {hx(p['ALU'])}")        # N
    a("k_alu_loop:")
    a("ADDR A A B")                    # a += b
    a("COPY E A")
    a("SHLV E 7")
    a("XORR A A E")                    # a ^= (a<<7)
    a("COPY E B")
    a("SHRV E 3")
    a("SUBR A A E")                    # a -= (b>>3)
    a("ADDR B B A")                    # b += a
    a("COPY E B")
    a("SHLV E 11")
    a("XORR B B E")                    # b ^= (b<<11)
    a("ADDR B B C")                    # b += i
    a("INCR C")
    a("CMPRR C D")
    a("JMPULT k_alu_loop:")
    a("RET")
    a("")

    # k_mem: streaming read+write then read over a >L1 buffer
    a("// ---- k_mem: for r: (for i: b[i]=b[i]+i+r) ; (for i: sum+=b[i]) ----")
    a("k_mem:")
    a(f"SETR A {hx(p['BUF'])}")        # base
    a(f"SETR B {hx(p['MEM_WORDS'])}")  # n
    a("SETR C 0")                      # r
    a("SETR64 H 0")                    # sum
    a("k_mem_rloop:")
    a("SETR D 0")                      # i
    a("COPY E A")                      # ptr
    a("k_mem_rw:")
    a("MEMGET64 F E")                  # F = b[i]
    a("ADDR F F D")                    # + i
    a("ADDR F F C")                    # + r
    a("MEMSET64 F E")                  # b[i] = F
    a("ADDV E 8")
    a("INCR D")
    a("CMPRR D B")
    a("JMPULT k_mem_rw:")
    a("SETR D 0")                      # i
    a("COPY E A")                      # ptr
    a("k_mem_r:")
    a("MEMGET64 F E")
    a("ADDR H H F")                    # sum += b[i]
    a("ADDV E 8")
    a("INCR D")
    a("CMPRR D B")
    a("JMPULT k_mem_r:")
    a("INCR C")
    a(f"CMPRV C {hx(p['MEM_REPS'])}")
    a("JMPULT k_mem_rloop:")
    a("RET")
    a("")

    # build_perm: Sattolo permutation of BUF[0..n-1] (setup, outside window)
    a("// ---- build_perm: b[i]=i then Sattolo shuffle (xorshift32 rng) ----")
    a("build_perm:")
    a(f"SETR A {hx(p['BUF'])}")        # base
    a(f"SETR B {hx(p['MEM_WORDS'])}")  # n
    a("SETR C 0")                      # i
    a("COPY E A")                      # ptr
    a("build_perm_init:")
    a("MEMSET64 C E")                  # b[i] = i
    a("ADDV E 8")
    a("INCR C")
    a("CMPRR C B")
    a("JMPULT build_perm_init:")
    a("SETR G 0x2545F491")             # rng (32-bit)
    a("COPY C B")
    a("MINUSV C 1")                    # i = n-1
    a("build_perm_shuf:")
    a("CMPRV C 0")
    a("JMPE build_perm_done:")         # while i > 0
    # xorshift32: rng^=rng<<13; rng^=rng>>17; rng^=rng<<5 (mask to 32 bits)
    a("COPY H G")
    a("SHLV H 13")
    a("XORR G G H")
    a("ANDV G 0xFFFFFFFF")
    a("COPY H G")
    a("SHRV H 17")
    a("XORR G G H")
    a("ANDV G 0xFFFFFFFF")
    a("COPY H G")
    a("SHLV H 5")
    a("XORR G G H")
    a("ANDV G 0xFFFFFFFF")
    a("MODUR D G C")                   # j = rng % i  (0..i-1)
    # swap b[i], b[j]: addr_i = BUF + i*8, addr_j = BUF + j*8
    a("COPY E C")
    a("SHLV E 3")
    a("ADDR E E A")                    # &b[i]
    a("COPY F D")
    a("SHLV F 3")
    a("ADDR F F A")                    # &b[j]
    a("MEMGET64 H E")                  # t = b[i]
    a("MEMGET64 I F")                  # u = b[j]
    a("MEMSET64 I E")                  # b[i] = u
    a("MEMSET64 H F")                  # b[j] = t
    a("MINUSV C 1")                    # i--
    a("JMP build_perm_shuf:")
    a("build_perm_done:")
    a("RET")
    a("")

    # k_chase: dependent pointer chase over the permuted buffer
    a("// ---- k_chase: idx = b[idx]; acc += idx  (dependent-load chain) ----")
    a("k_chase:")
    a(f"SETR A {hx(p['BUF'])}")        # base
    a("SETR C 0")                      # idx
    a("SETR64 H 0")                    # acc
    a("SETR D 0")                      # i
    a(f"SETR E {hx(p['CHASE'])}")      # steps
    a("k_chase_loop:")
    a("COPY F C")
    a("SHLV F 3")                      # idx*8
    a("ADDR F F A")                    # &b[idx]
    a("MEMGET64 C F")                  # idx = b[idx]
    a("ADDR H H C")                    # acc += idx
    a("INCR D")
    a("CMPRR D E")
    a("JMPULT k_chase_loop:")
    a("RET")
    a("")

    # k_branch: xorshift PRNG + 3 data-dependent branches
    a("// ---- k_branch: prng then ~50%/~25%/~6% taken branches ----")
    a("k_branch:")
    a("SETR A 0x1234567")              # rng
    a("SETR64 H 0")                    # cnt
    a("SETR D 0")                      # i
    a(f"SETR E {hx(p['BR'])}")         # iters
    a("k_branch_loop:")
    a("COPY F A")
    a("SHLV F 13")
    a("XORR A A F")
    a("ANDV A 0xFFFFFFFF")
    a("COPY F A")
    a("SHRV F 17")
    a("XORR A A F")
    a("ANDV A 0xFFFFFFFF")
    a("COPY F A")
    a("SHLV F 5")
    a("XORR A A F")
    a("ANDV A 0xFFFFFFFF")
    a("COPY F A")
    a("ANDV F 0x80000000")            # if (rng & 0x80000000) cnt++
    a("CMPRV F 0")
    a("JMPE k_branch_b2:")
    a("ADDV H 1")
    a("k_branch_b2:")
    a("COPY F A")
    a("ANDV F 0xFF")                  # if ((rng & 0xff) < 64) cnt += 2
    a("CMPRV F 64")
    a("JMPUGE k_branch_b3:")
    a("ADDV H 2")
    a("k_branch_b3:")
    a("COPY F A")
    a("ANDV F 0xF00")                 # if ((rng & 0xf00) == 0) cnt += 3
    a("CMPRV F 0")
    a("JMPNE k_branch_next:")
    a("ADDV H 3")
    a("k_branch_next:")
    a("INCR D")
    a("CMPRR D E")
    a("JMPULT k_branch_loop:")
    a("RET")
    a("")

    # fib: naive recursion (CALL/RET + stack)
    a("// ---- fib(A) -> M  (naive recursion; exercises CALL/RET/stack) ----")
    a("fib:")
    a("CMPRV A 2")
    a("JMPUGE fib_rec:")
    a("COPY M A")                     # n<2: return n
    a("RET")
    a("fib_rec:")
    a("PUSH A")                       # save n
    a("MINUSV A 1")
    a("CALL fib:")                    # M = fib(n-1)
    a("POP A")                        # restore n
    a("PUSH M")                       # save fib(n-1)
    a("MINUSV A 2")
    a("CALL fib:")                    # M = fib(n-2)
    a("POP A")                        # A = fib(n-1)
    a("ADDR M A M")                   # M = fib(n-1)+fib(n-2)
    a("RET")
    a("")
    a("k_fib_top:")
    a(f"SETR A {hx(p['FIB'])}")
    a("CALL fib:")
    a("RET")
    a("")

    # k_muldiv: 64-bit multiply + divide + modulo loop
    a("// ---- k_muldiv: a*=i; acc += a/(i|1); acc ^= a%(i|3) ----")
    a("k_muldiv:")
    a("SETR64 A 0x9E3779B97F4A7C15")   # a
    a("SETR64 H 0")                    # acc
    a("SETR C 1")                      # i
    a(f"SETR D {hx(p['MD'])}")         # MD_ITERS
    a("k_muldiv_loop:")
    a("MULR A A C")                    # a = a*i
    a("COPY E C")
    a("ORV E 1")                       # i|1
    a("DIVUR F A E")                   # a/(i|1)
    a("ADDR H H F")
    a("COPY E C")
    a("ORV E 3")                       # i|3
    a("MODUR F A E")                   # a%(i|3)
    a("XORR H H F")
    a("INCR C")
    a("CMPRR C D")
    a("JMPULE k_muldiv_loop:")         # i <= MD_ITERS
    a("RET")

    return "\n".join(L) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in PROFILES:
        sys.exit("usage: gen_probe.py {sim|board}")
    p_name = sys.argv[1]
    sys.stdout.write(gen(PROFILES[p_name]))
